// fiaq-app/src/lib/components/chat/ChatComposer.svelte
<script lang="ts">
  import { tick } from 'svelte'
  import FiaqIcon from '$lib/components/FiaqIcon.svelte'
  import Button from '$lib/components/ui/button.svelte'
  import Textarea from '$lib/components/ui/textarea.svelte'

  interface Props {
    disabled: boolean
    keyboardMode?: boolean
    onSend?: (text: string) => void
    onFocus?: () => void
    onBlur?: () => void
  }

  let { disabled, keyboardMode = false, onSend, onFocus, onBlur }: Props = $props()
  let text = $state('')
  let textareaEl: HTMLTextAreaElement | null = null

  function resize(el = textareaEl) {
    if (!el) return
    el.style.height = 'auto'
    el.style.height = `${Math.min(el.scrollHeight, 176)}px`
  }

  async function handleSend() {
    const trimmed = text.trim()
    if (!trimmed) return
    onSend?.(trimmed)
    text = ''
    await tick()
    resize()
  }

  function handleInput(event: Event) {
    textareaEl = event.currentTarget as HTMLTextAreaElement
    resize(textareaEl)
  }

  function handleFocus(event: FocusEvent) {
    textareaEl = event.currentTarget as HTMLTextAreaElement
    onFocus?.()
    requestAnimationFrame(() => {
      textareaEl?.scrollIntoView({ block: 'nearest', behavior: 'smooth' })
    })
  }

  function handleKeydown(event: KeyboardEvent) {
    if (event.key !== 'Enter' || event.shiftKey || event.altKey || event.metaKey || event.ctrlKey) return
    event.preventDefault()
    void handleSend()
  }
</script>

<div class="shrink-0">
  <div
    class={[
      'group flex w-full items-end gap-2 rounded-[1.1rem] border bg-white/95 p-2 ring-1 ring-white/70 transition-[background-color,border-color,box-shadow] focus-within:border-[#00a155] focus-within:ring-4 focus-within:ring-[#00a155]/15 sm:rounded-[1.35rem] sm:p-2.5',
      keyboardMode
        ? 'border-[#00a155] shadow-[0_8px_28px_rgba(15,23,42,0.16)]'
        : 'border-slate-200 shadow-[0_14px_34px_rgba(15,23,42,0.12)] sm:shadow-[0_16px_44px_rgba(15,23,42,0.12)]'
    ]}
  >
    <span class="mb-2.5 hidden h-10 w-10 shrink-0 items-center justify-center rounded-2xl bg-slate-100 text-[#1a2e5a] transition-colors group-focus-within:bg-emerald-50 group-focus-within:text-[#00a155] sm:flex">
      <FiaqIcon name="i-lucide-message-circle" class="h-5 w-5" />
    </span>
    <Textarea
      bind:value={text}
      rows={1}
      name="chat-question"
      aria-label="Digite sua pergunta para o assistente"
      inputmode="text"
      placeholder="Digite sua pergunta..."
      disabled={disabled}
      enterkeyhint="send"
      autocomplete="off"
      autocapitalize="sentences"
      class="max-h-36 min-h-11 flex-1 resize-none border-0 bg-transparent px-2 py-2.5 text-base leading-6 text-[#142854] shadow-none outline-none placeholder:text-slate-400 focus-visible:ring-0 disabled:opacity-50 sm:max-h-44 sm:min-h-14 sm:py-3.5 sm:text-lg sm:leading-7"
      oninput={handleInput}
      onfocus={handleFocus}
      onblur={onBlur}
      onkeydown={handleKeydown}
    />
    <Button
      type="button"
      disabled={disabled || !text.trim()}
      aria-label="Enviar pergunta"
      title="Enviar pergunta"
      class="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-[#00a155] text-white shadow-sm transition-[background-color,box-shadow,color,transform] hover:-translate-y-0.5 hover:bg-[#079052] hover:shadow-md focus:outline-none focus-visible:ring-2 focus-visible:ring-green-400 disabled:translate-y-0 disabled:cursor-not-allowed disabled:bg-slate-200 disabled:text-slate-400 disabled:shadow-none sm:h-14 sm:w-14 sm:rounded-2xl"
      onclick={() => void handleSend()}
    >
      <FiaqIcon name="i-lucide-send" class="h-5 w-5" />
    </Button>
  </div>
</div>

// fiaq-app/app/components/chat/ChatComposer.vue
<template>
  <div class="shrink-0">
    <div class="group flex w-full items-end gap-2 rounded-[1.35rem] border border-slate-200 bg-white/95 p-2.5 shadow-[0_16px_44px_rgba(15,23,42,0.12)] ring-1 ring-white/70 transition-all focus-within:border-[#00a155] focus-within:ring-4 focus-within:ring-[#00a155]/15">
      <span class="mb-2.5 hidden h-10 w-10 shrink-0 items-center justify-center rounded-2xl bg-slate-100 text-[#1a2e5a] transition-colors group-focus-within:bg-emerald-50 group-focus-within:text-[#00a155] sm:flex">
        <UIcon
          name="i-lucide-message-circle"
          class="h-5 w-5"
        />
      </span>
      <textarea
        ref="textareaEl"
        v-model="text"
        rows="1"
        placeholder="Digite sua pergunta..."
        :disabled="disabled"
        class="max-h-44 min-h-14 flex-1 resize-none bg-transparent px-2 py-3.5 text-base leading-7 text-[#142854] outline-none placeholder:text-slate-400 disabled:opacity-50 sm:text-lg"
        @input="resize"
        @keydown="handleKeydown"
      />
      <button
        :disabled="disabled || !text.trim()"
        title="Enviar pergunta"
        class="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-[#00a155] text-white shadow-sm transition-all hover:-translate-y-0.5 hover:bg-[#079052] hover:shadow-md focus:outline-none focus-visible:ring-2 focus-visible:ring-green-400 disabled:translate-y-0 disabled:cursor-not-allowed disabled:bg-slate-200 disabled:text-slate-400 disabled:shadow-none"
        @click="handleSend"
      >
        <UIcon
          name="i-lucide-send"
          class="h-5 w-5"
        />
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { nextTick, ref } from 'vue'

defineProps<{ disabled: boolean }>()

const emit = defineEmits<{
  send: [text: string]
}>()

const text = ref('')
const textareaEl = ref<HTMLTextAreaElement | null>(null)

function resize() {
  const el = textareaEl.value
  if (!el) return
  el.style.height = 'auto'
  el.style.height = `${Math.min(el.scrollHeight, 176)}px`
}

function handleSend() {
  const trimmed = text.value.trim()
  if (!trimmed) return
  emit('send', trimmed)
  text.value = ''
  nextTick(resize)
}

function handleKeydown(event: KeyboardEvent) {
  if (event.key !== 'Enter' || event.shiftKey || event.altKey || event.metaKey || event.ctrlKey) return
  event.preventDefault()
  handleSend()
}
</script>
